# Generated by Django 6.1 on 2026-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
