# Generated by Django 6.1 on 2026-08-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_publisher_alter_book_options_and_more"),
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookloan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="catalog.bookedition",
                verbose_name="Книга",
            ),
        ),
    ]
