# Generated by Django 6.1 on 2026-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_alter_bookloan_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookloan",
            name="is_overdue",
            field=models.BooleanField(default=False, verbose_name="Возврат просрочен"),
        ),
    ]
