# Generated by Django 6.1 on 2026-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0003_bookloan_is_overdue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookloan",
            name="is_overdue",
        ),
        migrations.AddField(
            model_name="bookloan",
            name="loan_period_days",
            field=models.PositiveIntegerField(default=30, verbose_name="Срок выдачи в днях"),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ожидаемая дата возврата"),
        ),
        migrations.AlterField(
            model_name="bookloan",
            name="status",
            field=models.CharField(
                choices=[("active", "Выдана"), ("returned", "Возвращена")],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
