# Generated by Django 6.1 on 2026-08-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Издательство",
                "verbose_name_plural": "Издательства",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="available_copies",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publication_year",
        ),
        migrations.RemoveField(
            model_name="book",
            name="total_copies",
        ),
        migrations.AddField(
            model_name="author",
            name="pseudonym",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Псевдоним"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="original_language",
            field=models.CharField(
                default="Английский", max_length=50, verbose_name="Язык оригинала"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="original_title",
            field=models.CharField(
                default="test", max_length=255, verbose_name="Оригинальное название"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="writing_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год написания"
            ),
        ),
        migrations.CreateModel(
            name="BookEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название перевода"),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(verbose_name="Год издания"),
                ),
                ("language", models.CharField(max_length=50, verbose_name="Язык")),
                (
                    "total_copies",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Всего экземпляров"
                    ),
                ),
                (
                    "available_copies",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Доступно экземпляров"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="catalog.book",
                        verbose_name="Произведение",
                    ),
                ),
                (
                    "translators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="translations",
                        to="catalog.author",
                        verbose_name="Авторы перевода",
                    ),
                ),
                (
                    "publishers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editions",
                        to="catalog.publisher",
                        verbose_name="Издательства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Издание книги",
                "verbose_name_plural": "Издание книг",
                "db_table": "book_editions",
                "ordering": ["title"],
            },
        ),
    ]
