# Generated by Django 6.1 on 2026-08-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_publisher_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookedition",
            options={
                "ordering": ["title"],
                "verbose_name": "Изданная книга",
                "verbose_name_plural": "Изданные книги",
            },
        ),
    ]
